# Generated by Django 4.1.7 on 2023-03-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.BigIntegerField(max_length=200, verbose_name="phone"),
        ),
    ]
