# Generated by Django 4.1.7 on 2023-03-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.BigIntegerField(verbose_name="phone"),
        ),
    ]
