# Generated by Django 4.0 on 2023-03-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_languag_userprofile_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_verification_code',
            new_name='verification_code',
        ),
    ]
